### ISSUE TITLE
Broken highlight after upgrading to the last update

### ISSUE THREAD

**Issue by micnic** [TitanKing/Express.tmTheme#1]
After updating to the last sublime text version (build 3103) the highlight is broken
![capture](https://cloud.githubusercontent.com/assets/1449826/12951126/76d71f9e-d019-11e5-85aa-b58461c3ee7c.PNG)

**Comment by TitanKing** [comment]
I will see what I can do to fix it. I am currently on V2.0.2 so I cant really test it. But I will make a plan.

**Comment by micnic** [comment]
@TitanKing thank you, I like a lot your color theme and really apreciate your work :)

**Comment by TitanKing** [comment]
Thanks man, kind of you.

**Comment by micnic** [comment]
Hello there, it seems that the bug that I reported is actually sublime text's bug
https://forum.sublimetext.com/t/javascript-syntax-highlighting-changes-in-3103/17328, I just did not observe it with other color themes, will close this and will roll back to 3083 to be able to use your color theme :)
